name: contacts_service
description: A Flutter plugin to retrieve and manage contacts on Android and iOS devices.
version: 0.0.9
author: Clovis Nicolas <clovisnicolas0@gmail.com>
homepage: https://github.com/clovisnicolas/flutter_contacts

environment:
  sdk: ">=2.0.0-dev.58.0.flutter-f981f09760 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: flutter.plugins.contactsservice.contactsservice
    pluginClass: ContactsServicePlugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.3.0